export const hotelTypes = [
    "Luxury",
    "Boutique",
    "Resort",
    "Budget",
    "Hostel",
    "Business",
    "Apartment",
    "Bed and Breakfast",
    "Motel",
    "Villa",
    "Cabin",
    "Lodge",
    "Inn",
    "Others",   ];

    export const hotelFacilities = [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Bar",
        "Parking",
        "Airport Shuttle",
        "Pet Friendly",
        "Room Service",
        "Laundry Service",
        "Business Center",
        "Conference Rooms",
        "Non-Smoking Rooms",
        "Breakfast Included",
        "Private Beach",
        "Infinity Pool",
        "Butler Service",
        "Gourmet Restaurant",
        "Rooftop Bar",
        "Spa and Wellness Center",
        "Jacuzzi",
        "Private Balcony",
     ]
     